### ISSUE TITLE
Unimplemented Function

### ISSUE THREAD

**Issue by AndreasBergmeister** [Karami-m/HiGen_main#1]
`create_graphs_multilevel` in `higen_runner.py` is not implemented.

**Comment by mzf666** [comment]
Same issues. Is this issue fixed yet?

**Comment by Karami-m** [comment]
Fixed in the new commit. Please check  the instruction `README.md` if you want to test on new graph dataset; in this case, the code first preprocess the graphs into the hierarchical-graph dataset. Otherwise if you want to test it on the datasets reported in the paper, you can simply unzip the dataset files which include the preprocessed the hierarchical-graph data.
